version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
  db:
    image: postgres:13.8
    container_name: postgresql
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    container_name: django
    command: sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l INFO
    volumes:
      - ./src:/app
    container_name: celery
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - app

  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A core beat -l info
    volumes:
      - ./src:/app
    container_name: celery-beat
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - app


volumes:
  pgdata: