# Generated by Django 4.1.5 on 2023-03-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_first_name_alter_user_last_name"),
        ("blog", "0014_alter_comment_comment_post_favoritepost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritepost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
        migrations.AlterField(
            model_name="favoritepost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favoritepost",
                to="accounts.profile",
            ),
        ),
    ]
